---
# SPDX-FileCopyrightText: 2023 CERN (home.cern)
#
# SPDX-License-Identifier: BSD-3-Clause

version: '1.0.0'
name: 'FMC ADC 100M 14b 4cha'
description: 'https://raw.githubusercontent.com/wiki/vascoguita/fmc-adc-100m14b4cha/Home.md'
website: 'https://ohwr.org/project/fmc-adc-100m14b4cha'
licenses:
  - 'CC-BY-SA-4.0'
  - 'CC0-1.0'
  - 'CERN-OHL-W-2.0'
  - 'GPL-2.0-or-later'
  - 'GPL-3.0-or-later'
images:
  - 'https://ohwr.org/project/fmc-adc-100m14b4cha/uploads/c812d406ca2b548917d8ff6a4c9301f4/fmc-adc_v3_top.jpg'
  - 'https://ohwr.org/project/fmc-adc-100m14b4cha/uploads/669878f74ff69e386880d0d4394af9bd/fmc-adc_v3_front.jpg'
documentation: 'https://ohwr.org/project/fmc-adc-100m14b4cha/wikis'
issues: 'https://ohwr.org/project/fmc-adc-100m14b4cha/issues'
latest_release: 'https://ohwr.org/project/fmc-adc-100m14b4cha/tags/v6.0.4'
forum: 'https://forums.ohwr.org/c/fmc-adc-100m14b4cha'
newsfeed: 'https://raw.githubusercontent.com/wiki/vascoguita/fmc-adc-100m14b4cha/News.md'
links:
  - name: 'FAQ'
    url: 'https://ohwr.org/project/fmc-adc-100m14b4cha/wikis/FAQ'
  - name: 'An informal description of the design'
    url: 'https://www.ohwr.org/project/fmc-adc-100m14b4cha-hw/uploads/952e4a8d5d07883be5a00a6be7970657/fmc-adc_informal_description.pdf'
  - name: 'Datasheet LTC2175-14/LTC2174-14/LTC2173-14 - 14-Bit, 125Msps/105Msps/80Msps Low Power Quad ADCs'
    url: 'https://ohwr.org/project/fmc-adc-100m14b4cha-hw/wikis/uploads/58fd29ca0dd780866f9691f5f30dd3a4/LTC2174.pdf'
  - name: 'Estimation of the performance of the FmcAdc100M14b4cha with higher input impedance'
    url: 'https://www.ohwr.org/project/fmc-adc-100m14b4cha-hw/uploads/1e61f65d5eb38803625791e54e3c4f5b/1M_input_impedance_study.pdf'
  - name: 'Simple bill of materials and prices of the truncated versions of the FmcAdc (reduced capability)'
    url: 'https://www.ohwr.org/project/fmc-adc-100m14b4cha-hw/uploads/e1de4814081e6835d901980f7383de0e/fmc-adc_simple_bom_different_variants.pdf'
  - name: 'Power consumption measurements of ADC on SPEC carrier'
    url: 'https://ohwr.org/project/fmc-adc-100m14b4cha-hw/wikis/PowerConsumption'
  - name: 'Current consumption measurements (30/7/2010)'
    url: 'https://www.ohwr.org/project/fmc-adc-100m14b4cha-hw/uploads/01a018ddca7171b28cf01a31d7f6e000/fmc-adc_current_consumption.pdf'
