`define AUX_TRIGIN_SIZE 20
`define ADDR_AUX_TRIGIN_VERSION 'h0
`define AUX_TRIGIN_VERSION_PRESET 'hadc10001
`define ADDR_AUX_TRIGIN_CTRL 'h4
`define AUX_TRIGIN_CTRL_ENABLE_OFFSET 0
`define AUX_TRIGIN_CTRL_ENABLE 'h1
`define ADDR_AUX_TRIGIN_SECONDS 'h8
`define ADDR_AUX_TRIGIN_CYCLES 'h10
